// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using JimHalpert.App.ViewModel;
using System;
using System.Collections.Generic;

namespace JimHalpert.App.ViewModel
{
    public partial class CidadeViewModel
    {
        public CidadeViewModel()
        {
            Cliente = new HashSet<ClienteViewModel>();
        }

        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public short EstadoId { get; set; }

        public virtual EstadoViewModel Estado { get; set; }
        public virtual ICollection<ClienteViewModel> Cliente { get; set; }
    }
}