// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.App.ViewModel
{
    public partial class MesViewModel
    {
        public byte MesId { get; set; }
        public string Nome { get; set; }
    }
}