// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Application.ViewModel
{
    public partial class CorViewModel
    {
        public int CorId { get; set; }
        public string Nome { get; set; }
    }
}