// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Entity
{
    public partial class Estado
    {
        public Estado()
        {
            Cidade = new HashSet<Cidade>();
        }

        public short EstadoId { get; set; }
        public string SiglaUf { get; set; }
        public string NomeUf { get; set; }

        public virtual ICollection<Cidade> Cidade { get; set; }
    }
}