// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Entity
{
    public partial class Tarefa
    {
        public Tarefa()
        {
            ComposicaoNotaFiscal = new HashSet<ComposicaoNotaFiscal>();
            TarefaItem = new HashSet<TarefaItem>();
        }

        public int TarefaId { get; set; }
        public int ClienteId { get; set; }
        public string Nome { get; set; }
        public string Observacao { get; set; }
        public decimal? ValorOrcado { get; set; }
        public DateTime? DataInicio { get; set; }
        public DateTime? DataFim { get; set; }

        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<ComposicaoNotaFiscal> ComposicaoNotaFiscal { get; set; }
        public virtual ICollection<TarefaItem> TarefaItem { get; set; }
    }
}