// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class Cidade
    {
        public Cidade()
        {
            Cliente = new List<Cliente>();
        }

        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public short EstadoId { get; set; }

        public virtual Estado Estado { get; set; }
        public virtual List<Cliente> Cliente { get; set; }
    }
}