// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class Faturamento
    {
        public int FaturamentoId { get; set; }
        public int ClienteId { get; set; }
        public int Ano { get; set; }
        public int Mes { get; set; }
        public decimal Valor { get; set; }

        public virtual Cliente Cliente { get; set; }
    }
}