// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class Mes
    {
        public int MesId { get; set; }
        public string Nome { get; set; }
    }
}