// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class NotaFiscal
    {
        public NotaFiscal()
        {
            ArquivoNotaFiscal = new List<ArquivoNotaFiscal>();
            ComposicaoNotaFiscal = new List<ComposicaoNotaFiscal>();
            TributoNotaFiscal = new List<TributoNotaFiscal>();
        }

        public int NotaFiscalId { get; set; }
        public string Numero { get; set; }
        public int ClienteId { get; set; }
        public string CodigoVerificacao { get; set; }
        public DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public decimal ImpostoTotalRetido { get; set; }
        public decimal ValorLiquido { get; set; }
        public string Descricao { get; set; }
        public int StatusNotaFiscalId { get; set; }

        public virtual Cliente Cliente { get; set; }
        public virtual StatusNotaFiscal StatusNotaFiscal { get; set; }
        public virtual List<ArquivoNotaFiscal> ArquivoNotaFiscal { get; set; }
        public virtual List<ComposicaoNotaFiscal> ComposicaoNotaFiscal { get; set; }
        public virtual List<TributoNotaFiscal> TributoNotaFiscal { get; set; }
    }
}