// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class Servico
    {
        public Servico()
        {
            TarefaItem = new HashSet<TarefaItem>();
        }

        public int ServicoId { get; set; }
        public string Descricao { get; set; }

        public virtual ICollection<TarefaItem> TarefaItem { get; set; }
    }
}