// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class TipoDeCliente
    {
        public TipoDeCliente()
        {
            Cliente = new List<Cliente>();
        }

        public byte TipoDeClienteId { get; set; }
        public string Descricao { get; set; }

        public virtual List<Cliente> Cliente { get; set; }
    }
}