// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JimHalpert.Domain.Entity
{
    public partial class Usuario
    {
        public Usuario()
        {

        }

        public int UsuarioId { get; set; }
        public string Login { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Documento { get; set; }
        public byte[] Senha { get; set; }
        public string SenhaTexto { get; set; }
        public DateTime DataNascimento { get; set; }
        public DateTime DataLogin { get; set; }
        public DateTime DataCriacao { get; set; }
        public DateTime DataAtualizacao { get; set; }
        public DateTime ValidadeSenha { get; set; }
        public bool Admin { get; set; }
        public bool Ativo { get; set; }

    }
}